name: "Check auto-mergeability of PR"
on:
  # use pull_request_target to also run on PRs with merge conflict
  pull_request_target:
    types: [labeled, unlabeled, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  contents: read
  statuses: write
  pull-requests: write
  issues: write

jobs:
  action:
    name: check-auto-mergeability-of-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: flyingcircusio/fc-nixos-release-tools
          ref: 'PL-133248-auto-merge'
      - uses: cachix/install-nix-action@v30
      - name: build release tooling
        run: |
          nix build .#
      - run: |
          ./result/bin/auto-merge check-pr ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
